AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Gateway VPC Endpoint for ECR image pulls'

Parameters:
  VpcId:
    Type: String
    Default: vpc-09428a030461053cd
  RouteTableIds:
    Type: CommaDelimitedList
    Default: "rtb-042ba664e3bb37bb6"

Resources:
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds: !Ref RouteTableIds
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: '*'

Outputs:
  S3EndpointId:
    Description: S3 Gateway VPC Endpoint ID
    Value: !Ref S3GatewayEndpoint
